name: flutter_steem_wallet_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.1.4
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  logger: ^1.0.0
  flutter_svg: ^0.22.0
  shared_preferences: ^2.0.6
  flutter_secure_storage: ^4.2.0
  dio: ^4.0.0
  intl: ^0.17.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  pedantic: ^1.11.0
  build_runner: ^2.0.4
  hive_generator: ^1.1.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/icon/token-sbd.svg
    - assets/images/icon/token-steem-power.svg
    - assets/images/icon/token-steem.svg
    - assets/images/steem_logo_with_text.png
    - assets/images/steem_logo.webp
    - assets/images/start_background.jpeg
  uses-material-design: true

